server:
  port: 8000

spring:
  application:
    name: 'quizwiz'
  data:
    mongodb:
      host: ${DATABASE_HOST:localhost}
      username: ${DATABASE_USER:root}
      password: ${DATABASE_PASSWORD:password}
      port: ${DATABASE_PORT:27017}
